version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio_mc:
    image: minio/mc:latest
    container_name: minio_client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc rm --force myminio/my-bucket;
      /usr/bin/mc mb myminio/my-bucket;
      /usr/bin/mc policy download myminio/my-bucket;
      /usr/bin/mc rm --force myminio/static;
      /usr/bin/mc mb myminio/static;
      /usr/bin/mc policy download myminio/static;
      exit 0;
      "

volumes:
  postgres_data:
  minio_data:
  redis_data:

